Check for failures in load test processing workflow

diff --git a/.github/workflows/process-load-test-result.yml b/.github/workflows/process-load-test-result.yml
--- a/.github/workflows/process-load-test-result.yml
+++ b/.github/workflows/process-load-test-result.yml
@@ -18,6 +18,7 @@ jobs:
           branch_name="load-test-results"
           git pull
           git checkout -b $branch_name
+          git checkout -b "load-test-results"
           echo '${{ toJson(github.event.client_payload.results) }}' | jq -c '.[]' |
           while read -r result; do
             status=$(echo "$result" | jq -r '.status')
@@ -36,6 +37,9 @@ jobs:
           git push origin "${branch_name}"
         env:
           GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
+      - name: Push results
+        if: ${{ steps.processResults.outputs.hasPassed }}
+        run: git push origin "load-test-results"
       - name: Create pull request for new summary
         id: createPR
         if: ${{ steps.processResults.outputs.hasPassed }}
@@ -44,9 +48,9 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
       - name: Approve PR
         if: ${{ steps.processResults.outputs.hasPassed }}
-          run: |
-            sleep 5
-            gh pr review --approve ${{ steps.createPR.outputs.prUrl }}
+        run: |
+          sleep 5
+          gh pr review --approve ${{ steps.createPR.outputs.prUrl }}
         env:
           GITHUB_TOKEN: ${{ secrets.BALLERINA_REVIEWER_BOT_TOKEN }}
       - name: Merge PR
@@ -54,9 +58,18 @@ jobs:
         run: |
           status="NOT COMPLETED"
           while [ ! -z "$status" ]
+          checkCount="0"
+          while [ "$checkCount" != "3" ]
           do
             sleep 20
             status=$(gh pr status --jq '.currentBranch .statusCheckRollup[] | select(.status!="COMPLETED") | select(.context!="license/cla")' --json statusCheckRollup)
+            checkCount=$(gh pr status --jq '[.currentBranch .statusCheckRollup[] | select((.conclusion=="SUCCESS") and ((.name=="Build on Ubuntu") or (.name=="Build on Windows") or (.name=="codecov/project")))] | length' --json statusCheckRollup)
+            failedCount=$(gh pr status --jq '[.currentBranch .statusCheckRollup[] | select((.conclusion=="FAILURE") and ((.name=="Build on Ubuntu") or (.name=="Build on Windows") or (.name=="codecov/project")))]|length' --json statusCheckRollup)
+            if [[ "$failedCount" != "0" ]]
+            then
+              echo "PR Build has failed"
+              exit 1
+            fi
           done
           sleep 20
           gh pr merge --merge --delete-branch
